version: '3.1'
services:
  stats-server:
    build:
      context: ./statistic/server
      dockerfile: Dockerfile
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db/ewm-stats

  stats-db:
    image: postgres:15-alpine
    restart: always
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  #ewm-service:
  # ports:
  #    - "8080:8080"

  #ewm-db:
  #  image: postgres:14-alpine
